language: ruby
services:
  - postgresql
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database alki_test;' -U postgres
env:
  - DATABASE_URL="postgres://postgres@localhost/alki_test"
